#!/usr/bin/bash

python sample_ratings.py < ../data_sample/training_set_pre_2005.txt > unpruned_pairs.txt
python prune.py  unpruned_pairs.txt < ../data_sample/training_set_pre_2005.txt > pruned_pairs.txt
python check.py pruned_pairs.txt < ../data_sample/test_set_eq_2005.txt 

